import { useEffect, useRef, useState } from 'react';
import type { CategoryMap } from '@/types/product';
import type { TicketCategory } from '@/types/static-data';
import type { TicketOption } from '@/types/product';

interface InteractiveSeatMapProps {
  svgUrl: string;
  /**
   * Real mapping from the API's seating_plan.category_map. When omitted, a
   * mock mapping is generated by distributing the SVG's sections across the
   * event's ticket categories (prototype mode — sandbox has no real data).
   */
  categoryMap?: CategoryMap[];
  tickets: TicketOption[];
  categories: TicketCategory[];
  /** Scroll-to / highlight the ticket option for a clicked section */
  onSectionSelect?: (ticketCategoryId: number) => void;
  isPrototypeData?: boolean;
}

interface TooltipState {
  x: number;
  y: number;
  title: string;
  detail: string;
}

/**
 * Interactive stadium map in the style of ticketed.com: the venue SVG's
 * section paths (id="p-<n>") are tinted with each ticket category's color,
 * hover shows category + price, click jumps to that ticket option.
 *
 * The API contract this implements: seating_plan.image is the SVG and
 * category_map links ticket_category_id -> path_ids (path id 6915 = "#p-6915").
 */
export function InteractiveSeatMap({
  svgUrl,
  categoryMap,
  tickets,
  categories,
  onSectionSelect,
  isPrototypeData = false,
}: InteractiveSeatMapProps) {
  const containerRef = useRef<HTMLDivElement>(null);
  const [tooltip, setTooltip] = useState<TooltipState | null>(null);
  const [loadFailed, setLoadFailed] = useState(false);

  useEffect(() => {
    const container = containerRef.current;
    if (!container) return;
    let cancelled = false;
    const cleanups: (() => void)[] = [];

    (async () => {
      try {
        const res = await fetch(svgUrl);
        if (!res.ok) throw new Error(`SVG fetch failed: ${res.status}`);
        const text = await res.text();
        if (cancelled) return;

        // Build off-DOM and swap in atomically at the end, so effect re-runs
        // (live price refresh, dev StrictMode) never flash an empty panel
        const staging = document.createElement('div');
        staging.innerHTML = text;
        const svg = staging.querySelector('svg');
        if (!svg) throw new Error('No <svg> in seating plan file');
        svg.removeAttribute('width');
        svg.removeAttribute('height');
        svg.style.width = '100%';
        svg.style.height = 'auto';

        // Sections carry ids like "p-6915"; the category map references the
        // numeric part
        const sections = [...svg.querySelectorAll<SVGElement>('[id^="p-"]')];

        let effectiveMap = categoryMap;
        if (!effectiveMap || effectiveMap.length === 0) {
          // Prototype mode: round-robin the venue's sections across the
          // event's actual ticket categories so real prices/colors show up
          const categoryIds = [
            ...new Set(tickets.map((t) => t.ticket_category)),
          ];
          if (categoryIds.length === 0) return;
          const buckets: CategoryMap[] = categoryIds.map((id) => ({
            ticket_category_id: id,
            path_ids: [],
          }));
          sections.forEach((el, i) => {
            buckets[i % buckets.length].path_ids.push(
              Number(el.id.replace('p-', ''))
            );
          });
          effectiveMap = buckets;
        }

        for (const entry of effectiveMap) {
          const category = categories.find(
            (c) => c.id === entry.ticket_category_id
          );
          const ticket = tickets.find(
            (t) => t.ticket_category === entry.ticket_category_id
          );
          if (!category) continue;

          for (const pathId of entry.path_ids) {
            const el = svg.querySelector<SVGElement>(`#p-${pathId}`);
            if (!el) continue;

            el.style.fill = category.color;
            el.style.opacity = ticket?.available ? '1' : '0.35';
            el.style.cursor = 'pointer';
            el.style.transition = 'filter 0.15s, opacity 0.15s';

            const onEnter = () => {
              el.style.filter = 'brightness(0.8)';
            };
            const onLeave = () => {
              el.style.filter = '';
              setTooltip(null);
            };
            const onMove = (e: MouseEvent) => {
              const rect = container.getBoundingClientRect();
              setTooltip({
                x: e.clientX - rect.left,
                y: e.clientY - rect.top,
                title: category.name,
                detail: ticket?.available
                  ? `£${ticket.price.toFixed(2)}`
                  : 'Sold out',
              });
            };
            const onClick = () => onSectionSelect?.(category.id);

            el.addEventListener('mouseenter', onEnter);
            el.addEventListener('mouseleave', onLeave);
            el.addEventListener('mousemove', onMove);
            el.addEventListener('click', onClick);
            cleanups.push(() => {
              el.removeEventListener('mouseenter', onEnter);
              el.removeEventListener('mouseleave', onLeave);
              el.removeEventListener('mousemove', onMove);
              el.removeEventListener('click', onClick);
            });
          }
        }

        container.replaceChildren(svg);
      } catch (error) {
        console.error('Seat map failed to load:', error);
        if (!cancelled) setLoadFailed(true);
      }
    })();

    // Don't clear the container here: the next run swaps content atomically,
    // and clearing on deps-change would blank the map until its fetch resolves
    return () => {
      cancelled = true;
      cleanups.forEach((fn) => fn());
    };
  }, [svgUrl, categoryMap, tickets, categories, onSectionSelect]);

  if (loadFailed) return null;

  const legendCategories = [
    ...new Set(tickets.map((t) => t.ticket_category)),
  ]
    .map((id) => categories.find((c) => c.id === id))
    .filter((c): c is TicketCategory => Boolean(c));

  return (
    <div className="rounded-3xl border border-gray-200 bg-white p-8 shadow-card">
      <div className="flex flex-wrap items-center justify-between gap-2">
        <h2 className="font-display text-2xl font-bold">Pick your zone</h2>
        {isPrototypeData && (
          <span className="chip bg-gold-50 text-gold-700">
            Prototype — demo zone mapping
          </span>
        )}
      </div>

      <div className="relative mt-4">
        {/* SVG injected into this inner div; tooltip must stay a sibling
            because the injection replaces the container's children */}
        <div ref={containerRef} />
        {tooltip && (
          <div
            className="pointer-events-none absolute z-20 -translate-y-full rounded-xl bg-ink px-3 py-2 text-white shadow-card-hover"
            style={{ left: tooltip.x + 16, top: tooltip.y - 8 }}
          >
            <p className="text-sm font-semibold">{tooltip.title}</p>
            <p className="text-xs text-gray-300">{tooltip.detail}</p>
          </div>
        )}
      </div>

      {legendCategories.length > 0 && (
        <div className="mt-4 flex flex-wrap gap-x-6 gap-y-2">
          {legendCategories.map((category) => (
            <span
              key={category.id}
              className="flex items-center gap-2 text-sm text-ink-soft"
            >
              <span
                className="h-3 w-3 rounded-full border border-ink/10"
                style={{ backgroundColor: category.color }}
              />
              {category.name}
            </span>
          ))}
        </div>
      )}
      <p className="mt-3 text-sm text-ink-muted">
        Click a colored zone to jump to its ticket option.
      </p>
    </div>
  );
}
